services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: yt-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./fonts:/app/fonts
      - ./api/credentials:/app/api/credentials
    environment:
      - TZ=Asia/Jakarta
