services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: yt-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./tmp:/app/tmp      # ✅ boleh
      - ./data:/app/data    # ✅ boleh
    environment:
      - TZ=Asia/Jakarta
